version: '3'
services:
#mssql docker
  enaturebeauty-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - enaturebeautynet

  enaturebeauty-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:eNatureBeauty=Server=enaturebeauty-sql,1433;Database=170218;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 50347:80
    networks:
      - enaturebeautynet
    links:
      - enaturebeauty-sql
    depends_on:
      - enaturebeauty-sql
      
networks:
  enaturebeautynet:
    driver: bridge